#ifndef CIDBINDINGS_H
#define CIDBINDINGS_H
#pragma once

#endif // CIDBINDINGS_H

enum BINDING_ID {
    ID_TIMER_VIEW1_UPDATE,      // Updating for view 1
    ID_TIMER_VIEW2_UPDATE,      // Not used at the moment
    ID_TIMER_INFOTREE_UPDATE,   // Updating the information tree

    ID_MENU_SAVE_LOG,           // Menu buttons
    ID_MENU_SAVE_SNAPSHOT,
    ID_MENU_EXIT,
    ID_MENU_ABOUT,

    ID_BTN_ROBOT_CONNECT,       // Robot Notebook panel buttons
    ID_BTN_ROBOT_DISCONNECT,
    ID_BTN_ROBOT_UPDATE,
    ID_BTN_ROBOT_SEND_CMD,
    ID_BTN_ROBOT_SEND_POS,
    ID_BTN_ROBOT_SEND_HOME,
    ID_BTN_ROBOT_SEND_PICKUP,

    ID_BTN_GRIPPER_CONNECT,     // Gripper Notebook panel buttons
    ID_BTN_GRIPPER_DISCONNECT,
    ID_BTN_GRIPPER_GRIP,
    ID_BTN_GRIPPER_RELEASE,
    ID_BTN_GRIPPER_HOME,
    ID_BTN_GRIPPER_SEND_CMD,

    ID_BTN_CAMERA_START,      // Camera Notebook panel buttons
    ID_BTN_CAMERA_STOP,
    ID_BTN_CAMERA_RECALIBRATE,
    ID_BTN_CAMERA_FINDBALL,
    ID_BTN_CAMERA_CUT_TABLE,
    ID_BTN_CAMERA_LOAD_DETECTOR_SETTINGS,

    ID_BTN_DATABASE_CONNECT,    // Database Notebook panel buttons
    ID_BTN_DATABASE_DISCONNECT,
    ID_BTN_DATABASE_UPDATE,
    ID_BTN_DATABASE_UPDATE_TREE,
    ID_DATABASE_SUB_TREE,

    ID_BTN_TESTING_XYZ_VVA,      // Testing Notebook panel buttons
    ID_BTN_TESTING_DETECT_PICK
};
